### ISSUE TITLE
Very hard to use with angular2 cli

### ISSUE THREAD

**Issue by Joegrundman** [Caged/d3-tip#181]
The angular2 cli uses webpack to bundle the files, and really I have no idea how to integrate d3-tip.

d3 can be imported using

import * as d3 from 'd3'

but importing * as d3tip from 'd3-tip' for example doesn't work

There is also an option to install globally using the scripts field in angular-cli.json, but this also seems not to work

can anyone recommend how to do this, and what might be the problem?

When I import it, i can see  the file in the console, but i get the following message

```
EXCEPTION: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_1_d3__.tip is not a function
TypeError: __WEBPACK_IMPORTED_MODULE_1_d3__.tip is not a function
```

**Comment by vdh** [comment]
```js
import d3Tip from 'd3-tip';
```
Is the correct way to write that import statement.

When you use `import *`, you're actually saying "import everything that this module exports as this one object". What was once one giant module, `d3` is now a collection of smaller independent modules that can be imported separately for smaller dependencies.

For more information about ES6 modules, see this article about the `import` and `export` syntax:
http://www.2ality.com/2014/09/es6-modules-final.html
For more information about `d3`'s decision to move towards a collection of smaller libraries, see these release notes:
https://github.com/d3/d3/blob/master/CHANGES.md

**Comment by Joegrundman** [comment]
Hi vdh

Thank you very much for answering, and I apologize for the poor example I used with import `{* as d3Tip}`. I have  been bashing my head out on this one for a long time and I think there is a deeper issue here.

I have tried the following options. 

For example, yes i have tried

`import d3Tip from 'd3-tip'`

and also I have tried changing the d3-tip/index.js to export an es6 module so i can import it with

`import {d3Tip} from 'd3Tip'`

and I also tried using the d3Tip conversion to es6 by moglars
https://github.com/Caged/d3-tip/pull/166

and I have spent a lot of time on the typings files.

in all cases I am successfully importing the file. This can be seen using the chrome dev tools, but the problem is that the d3Tip.tip() function is not accessible, with the error message I have reported above, and I may be wrong here, but I have the feeling that this is related to the angular2-cli and its recent migration to webpack.

Reason: i came across this thread here:

http://stackoverflow.com/questions/39411091/d3-tip-doesnt-work-with-webpack

The author suggests there are some hoops that can be jumped through with a plugin, specifically 

`single-module-instance-webpack-plugin` and maybe also `dedupe-plugin`

but with angular2-cli one cannot directly access the webpack.config.js


and also this thread here:

http://stackoverflow.com/questions/40861009/using-plugins-for-d3-in-angular2

user Velko Ivanov suggests this may be a problem with the way webpack handles modules sharing namespace, in particular when the d3 object is initially declared as null and then has methods added through a series of internal function calls, which is how the d3 object is created.

At present I have given up on this and have been writing my own (inferior) tooltip, since it seemed to me very difficult. (btw, this tooltip should be part of the standard d3 library)

Look, if I am just being stupid, then that's great, very sorry for wasting your time.

**Comment by vdh** [comment]
@Joegrundman
> but the problem is that the d3Tip.tip() function is not accessible

Ahh, I think you need to be using `d3Tip()` instead? `d3.tip()` is only available on the `d3` global when loaded outside of AMD or CommonJS environments. As of `d3-tip@0.7.0` the CommonJS loader is anonymous (see explanation below).

*My original reply I was writing, before I noticed that:*
Which versions of `d3` and `d3-tip` are you using, and are you using? `d3-tip@^0.7` is designed for `d3@^4.2`, and `d3-tip@^0.6` is for `d3@^3`. There's also the `d3-tip@0.8.0-alpha.1` alpha in development for the `d3` micro libraries.

I've been using Webpack with `d3-tip@^0.7` + `d3@^4.2` and later `d3-tip@0.8.0-alpha.1` with the micro libraries, so it should be working within Webpack. ~~So this is either a Webpack config issue or a bug in `d3-tip` that would need patching.~~

I know that in earlier versions of `d3-tip`, the CommonJS version had a bit of a weird use case where it returned a factory that modified the `d3` variable passed into it, e.g.
```js
// d3-tip@0.6.8
import d3 from 'd3';
import d3TipFactory from 'd3-tip';
const d3Tip = d3TipFactory(d3);
const tip = d3Tip(); // or const tip = d3.tip();
```

With `0.7.0`, I updated it to properly use `require('d3')` and return an anonymous library, e.g. 
```js
// d3-tip@0.7.0
import d3Tip from `d3-tip`;
const tip = d3Tip();
```

**Comment by Joegrundman** [comment]
Thanks a  lot @vdh, that did it. It was a simple thing!

**Comment by bartread** [comment]
Unfortunately this still isn't working for me. I'm using Typescript 2.4 with D3 V4 and both of the above give a similar error:

```
import d3Tip from 'd3-tip';
const tip = d3Tip();
```

The above gives "Cannot invoke an expression whose type lacks a call signature. Type 'typeof' "C:/my_project_root/node_modules/@types/d3-tip/index" has no compatible call signatures." No surprise, but there is also no tip() method on there either.

If I try the more verbose solution:

import * as d3 from 'd3'; // This works fine with all pure d3 code
import d3TipFactory from 'd3-tip';
const d3Tip = d3TipFactory(d3);
const tip = d3Tip();

I get the same call signature error on `d3TipFactory(d3);`.

Whilst I'm sure I'm just doing something simple wrong I have to agree somewhat with the sentiment expressed in the title of this bug. Why is it so hard to import d3-tip? 

Thanks for the help!

**Comment by riteshsingh2k** [comment]
It is still not working   :+1: 
import d3Tip from 'd3-tip';
const tip = d3Tip();

I am getting error @types/d3-tip/index"' has no compatible call signatures.

**Comment by klteograss** [comment]
Yes, I am also having issue on importing d3-tip as above.

**Comment by dereklin** [comment]
import like this:
```
import * as d3Tip from 'd3-tip';
```

Use it like this:
```
this.tip = d3Tip().attr('class', 'd3-tip').html((d) => 'test' );
```
This seems to be a good starting point: http://bl.ocks.org/Caged/6476579

**Comment by juanargote** [comment]
Using d3-tip 0.7.1, @types/d3-tip 3.5.5, angular 5.2.4 and typescript 2.5.0 I had to import d3-tip using the code snippet below in one of my components:

```import * as d3 from "d3";
import * as d3Tip from "d3-tip";
(d3 as any).tip = d3Tip;```

This solution was suggested in a (StackOverflow answer)[https://stackoverflow.com/questions/45569419/d3-tip-is-not-a-function-webpack-and-typescript]. Then, in order to overcome a type check error when invoking the tooltip in the component visualization context I had to use the keyword `as`:

```this.svg.call(this.detectorTooltip as any);```

Hope this helps another poor soul trying to get this to work.

**Comment by dev-tuhindas** [comment]
thanks dereklin , your solution works for me i loved it

**Comment by jplew** [comment]
I created a (semi) working example in StackBlitz, check it out: https://stackblitz.com/edit/d3-tip-angular-example?file=app%2Fd3-chart%2Fd3-chart.component.ts

I say "semi" because the screen location of the tip is messed up. The tips are anchored at the top of the screen instead of appearing above the mouseover point. The console says it can't figure out the bounding box: 

    ERROR TypeError: Cannot read property 'target' of null at getScreenBBox

Perhaps someone smarter than me can help debug this and get it working properly.

Note, here is how to import the library in StackBlitz:

    import d3Tip from 'd3-tip' // works

This appears to be unique to StackBlitz projects, however, because the following import works fine for my offline Angular 6 project:

    import * as d3Tip from 'd3-tip' // doesn't work

However, in my actual offline project I haven't succeeded in getting my tips to show up. `tip.show` is calling fine, but my tips are invisible. I suspect it is due to the same problem reported in StackBlitz. Would appreciate any help.

**Comment by codyburleson** [comment]
This is what seems to be working for me.

```
import * as d3 from 'd3';
import d3Tip from 'd3-tip'

d3.tip = d3Tip;
const tip = d3.tip()
      .attr('class', 'd3-tip')
      .html(function(data) {
        return data.date.format('ll'); // Format: Sep 4 1986
      })
      .direction('n')
      .offset([-6, 0]);
```

**Comment by budkin76** [comment]
@jplew thank you so much for this. I'm just learning D3 now and I'm using it in an Angular 6 app, and your Stackblitz was the key to getting it to work.

**Comment by vijaykanta** [comment]
> Using d3-tip 0.7.1, @types/d3-tip 3.5.5, angular 5.2.4 and typescript 2.5.0 I had to import d3-tip using the code snippet below in one of my components:
> 
> ```
> import * as d3 from "d3";
> import * as d3Tip from "d3-tip";
> (d3 as any).tip = d3Tip;
> ```
> 
> This solution was suggested in a [StackOverflow answer](https://stackoverflow.com/questions/45569419/d3-tip-is-not-a-function-webpack-and-typescript). Then, in order to overcome a type check error when invoking the tooltip in the component visualization context I had to use the keyword `as`:
> 
> ```
> this.svg.call(this.detectorTooltip as any);
> ```
> 
> Hope this helps another poor soul trying to get this to work.

I am the poor soul here having tried every page from the web's book. This is best solution for me. Kudos.

```
(d3 as any).tip.show()
(d3 as any).tip.hide()
```
for anyone else trying to figure out.

EDIT: Uh oh! Unfortunately it's breaking the compiler. I get the errors

`ERROR TypeError: d3__WEBPACK_IMPORTED_MODULE_2__.tip is not a function`

**Comment by vijaykanta** [comment]
Okay, so going through many SO posts and tuts around, I found the d3-tip typings lib to be the culprit. I had to silently uninstall this
`npm uninstall @types/d3-tip`
Then I make changes like
```
import * as d3 from 'd3';
import * as d3Tip from 'd3-tip';
....

const tip = d3Tip.default()
.attr('class', 'd3-tip')
....
```
This tip can be used anywhere like
```
svg.call(tip)
// or
tip.show()
tip.hide()
```
Then I stop/start the angular server, the errors are all gone. Now hoping it will work finally. :)
